MODEL_2D:
  TYPE: "UNetResNet34"
MODEL_3D:
  TYPE: "SCN"
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
    pselab_paths: ("/mnt/cache/feiben/workspace/outputs/xmuda/nuscenes/usa_singapore/xmuda/pselab_data/train_singapore.npy",)
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 64
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  CLASS_WEIGHTS: [2.47956584, 4.26788384, 5.71114131, 3.80241668, 1.]
  XMUDA:
    lambda_xm_src: 0.0
    lambda_xm_trg: 0.0
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 32
  PERIOD: 50
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda