MODEL_2D:
  TYPE: "UNetResNet34"
MODEL_3D:
  TYPE: "SCN"
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 20000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  CLASS_WEIGHTS: [2.68678412, 4.36182969, 5.47896839, 3.89026883, 1.]
VAL:
  BATCH_SIZE: 32
  PERIOD: 50
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda