MODEL_2D:
  TYPE: "UNetResNet34"
MODEL_3D:
  TYPE: "SCN"
DATASET_SOURCE:
  SETTING: "usa2singapore"
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "preprocess"
    nuscenes_dir: "s3://dataset/nuScenes/original_raw_data/"  # only front cam images are needed
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000, 100000, 110000, 125000, 140000)
  MAX_ITERATION: 150000
TRAIN:
  BATCH_SIZE: 1
  SUMMARY_PERIOD: 2000
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.68678412, 4.36182969, 5.47896839, 3.89026883, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
VAL:
  BATCH_SIZE: 1
  PERIOD: 5000
OUTPUT_DIR: "nuscenes/usa_singapore/adas" #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda
