MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 10
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 10
DATASET_SOURCE:
  SETTING: "audi2kitti"
  TYPE: "A2D2SCN"
  TRAIN: ("train",)
  A2D2SCN:
    preprocess_dir: "audi/a2d2_preprocess"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "semantickiiti-preposses/preprocess"
    semantic_kitti_dir: "s3://feiben/semantickitti-dataset/"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000, 100000, 110000,120000,1400000)
  MAX_ITERATION: 150000
TRAIN:
  BATCH_SIZE: 1
  SUMMARY_PERIOD: 1000
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.89090012, 2.0585112, 3.1970535, 3.1111633, 1., 2.93751704, 1.92053733,
                  1.47886874, 1.04654198, 1.78266561]
  XMUDA:
    lambda_xm_src: 0.1
    lambda_xm_trg: 0.01
VAL:
  BATCH_SIZE: 1
  PERIOD: 5000
OUTPUT_DIR: "nuscenes/a2d2_semantic_kitti/adas"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda
